version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:8u212-jdk-stretch
    steps:
      - checkout
      - run:
          name: Verify
          command: sleep 30 && grep success control.txt
workflows:
  version: 2
  default:
    jobs:
      - test
